### PR TITLE
Use _build_{no_,}opt flags

### PR DESCRIPTION
**Pull request by JP-Ellis**
Uses the same method of enabling/disabling builds as in the tensorflow-rocm.

### CODE REVIEW

**Comment by acxz** [comment]
Yeah this is prob a good idea, thx for the PR!

**Review by acxz — CHANGES_REQUESTED** [review]
You are gonna have to bump the `pkgrel` and update the `.SRCINFO` so that the AUR recognizes this as an update.

**Comment by JP-Ellis** [comment]
I wasn't planning to as this does not change the produced package at all, and thus I don't see the need to make everyone reinstall this.

**Comment by JP-Ellis** [comment]
I made a typo in the original commit, hence the force push.

**Comment by acxz** [comment]
Sounds good!

**Pull request merged**
